# Generated by Django 3.1.7 on 2021-03-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='adj_close',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='پایانی'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='count',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='تعداد معاملات'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='high',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='بیشترین'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='low',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='کمترین'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='open',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='اولین'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='value',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ارزش معاملات'),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='volume',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='حجم معاملات'),
        ),
    ]
