# Generated by Django 3.1.7 on 2021-03-03 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_auto_20210303_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
