# Generated by Django 3.1.7 on 2021-03-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0003_symbol_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='close',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='آخرین معامله'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='eps',
            field=models.IntegerField(blank=True, null=True, verbose_name='eps'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='group_p_e_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='Group P/E'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='p_e_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='P/E'),
        ),
        migrations.AddField(
            model_name='symbol',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس صفحه سهم'),
        ),
    ]
