# Generated by Django 3.1.7 on 2021-03-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0004_auto_20210304_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='index',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
