# Generated by Django 3.1.7 on 2021-03-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0005_symbol_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='group_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام گروه'),
        ),
    ]
